/**
 * The floor attribution label and the check that enforces it.
 *
 * Coord's decision (2026-10-08, bead mwg-train-6ek): we consume web-uplift's published ruleset, and
 * every floor artifact and report we generate must say 'mwg-train deterministic baseline', so nobody
 * reads our deterministic mechanical floor as an official `web-uplift` result. The pin check verifies
 * the ruleset; this verifies the attribution.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { checkBaselineLabel, falseProvenance } from '../scripts/check-baseline-label.mjs';
import { labelDocuments } from '../scripts/label-baseline.mjs';
import { BASELINE_LABEL, baselineAttributionLine } from '../src/eval/ruleset.mjs';

const ROOT = resolve(import.meta.dirname, '..');

// The registry lives in the check script; importing it would run the CLI, so the reports are listed
// here as well. If a report is added to one list and not the other this test still passes, so the
// CLI test below covers the registry as a whole.
const REPORTS = [
  'docs/eval/conformance/booking.md',
  'docs/eval/conformance/account-recovery-identity.md',
  'docs/eval/conformance/booking-identity.md',
  'docs/eval/conformance/catalogue-identity.md',
  'docs/eval/conformance/contact-lead-identity.md',
  'docs/eval/conformance/event-registration-identity.md',
  'docs/pilot/YIELD.md',
  'docs/train/corpus/YIELD.md',
  'docs/train/corpus/records.json',
  'pilot/CORPUS.json',
  'docs/pilot/yield.json',
  'docs/pilot/records.json',
  'docs/eval/conformance/booking.json',
  'docs/eval/conformance/account-recovery-identity.json',
  'docs/eval/conformance/booking-identity.json',
  'docs/eval/conformance/catalogue-identity.json',
  'docs/eval/conformance/contact-lead-identity.json',
  'docs/eval/conformance/event-registration-identity.json',
  'docs/pilot/README.md',
  'docs/eval/conformance/README.md',
];

test('every registered floor report carries the label', () => {
  for (const path of REPORTS) {
    const text = readFileSync(join(ROOT, path), 'utf8');
    assert.ok(text.includes(BASELINE_LABEL), `${path} must carry '${BASELINE_LABEL}'`);
  }
  assert.deepEqual(checkBaselineLabel(REPORTS), []);
});

test('the label is one string shared by every writer', () => {
  assert.equal(BASELINE_LABEL, 'mwg-train deterministic baseline');
  assert.ok(baselineAttributionLine().includes(BASELINE_LABEL));
  // The disclaimer has to name the product it is disclaiming, otherwise it does not disclaim anything.
  assert.match(baselineAttributionLine(), /web-uplift/);
  assert.match(baselineAttributionLine(), /not an official/);
});

test('a report without the label fails the check', () => {
  const dir = mkdtempSync(join(tmpdir(), 'baseline-label-'));
  try {
    const path = join(dir, 'report.md');
    writeFileSync(path, '# A floor report\n\nstructural 0.805, target 0.75\n');
    const found = checkBaselineLabel([path]);
    assert.deepEqual(found.map((f) => f.code), ['LABEL_MISSING']);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('a report that claims web-uplift authorship fails even when labelled', () => {
  const dir = mkdtempSync(join(tmpdir(), 'baseline-label-'));
  try {
    const path = join(dir, 'report.md');
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThis is an official web-uplift result.\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThe report web-uplift generated.\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // The two evasions review named: a detector that only covered 'official web-uplift result' and
    // 'web-uplift generated' let both of these pass on an otherwise labelled report.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nGenerated by web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift's official baseline\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nnumbers from web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // Second-round evasions: an authoring verb, and a negation in a DIFFERENT clause that the old
    // 24-character lookback treated as disclaiming the claim.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift built this floor\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nNot a mock; built by web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift produced these numbers\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('our own disclaimer is not mistaken for a claim', () => {
  // The label line negates the phrase it contains. A check that flagged it would fail on every report
  // it is supposed to accept, which is the fastest way to get a check deleted.
  assert.equal(falseProvenance(baselineAttributionLine()), null);
  assert.equal(falseProvenance('This is not an official web-uplift result.'), null);
  assert.equal(falseProvenance('structural 0.805'), null);
  assert.equal(falseProvenance('This is an official web-uplift result.'), 'official web-uplift');
  // A mention is not a claim: naming the product as something we compare against is legitimate, and so
  // is a true statement about THEIR artefact. Flagging those would make the check wrong about the thing
  // it is right about, which is how a check gets disabled.
  assert.equal(falseProvenance('we compare our floor against the web-uplift catalogue'), null);
  assert.equal(falseProvenance('The canonical catalog published by web-uplift changed.'), null);
  assert.equal(falseProvenance('The ruleset published by web-uplift has 178 guides.'), null);
  assert.equal(falseProvenance('We did not use web-uplift for our floor.'), null);
});

test('a registered report that is missing fails rather than passing quietly', () => {
  // The registry is a claim that these reports exist and were checked. If one is gone, the claim is
  // false, and a check that skips missing files reports success having checked nothing.
  const found = checkBaselineLabel(['docs/eval/conformance/does-not-exist.md']);
  assert.deepEqual(found.map((f) => f.code), ['REPORT_MISSING']);
});

test('the relabel tool refuses anything that is not attribution-only', () => {
  // The guard is the point of the tool: a relabel that changed a measurement would be falsification.
  // Simulate it by pointing the tool at a document whose label fields already exist in a different form,
  // which makes the stripped comparison differ.
  const dir = mkdtempSync(join(tmpdir(), 'label-baseline-'));
  try {
    const path = join(dir, 'record.json');
    writeFileSync(path, JSON.stringify({ measured: 0.805, baseline_label: 'something else' }));
    const result = labelDocuments([path])[0];
    assert.equal(result.code, 'REFUSED_NOT_ATTRIBUTION_ONLY');
    assert.equal(JSON.parse(readFileSync(path, 'utf8')).baseline_label, 'something else', 'a refused write must not modify the file');

    // A clean document is labelled, and --check reports it without writing.
    const clean = join(dir, 'clean.json');
    writeFileSync(clean, JSON.stringify({ measured: 0.805 }));
    assert.equal(labelDocuments([clean], { check: true })[0].code, 'WOULD_LABEL');
    assert.equal(JSON.parse(readFileSync(clean, 'utf8')).baseline_label, undefined, '--check must not write');
    assert.equal(labelDocuments([clean])[0].code, 'LABELLED');
    assert.equal(JSON.parse(readFileSync(clean, 'utf8')).baseline_label, BASELINE_LABEL);
    assert.equal(labelDocuments([clean])[0].code, 'ALREADY_LABELLED', 'relabelling is idempotent');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('the CLI passes on the tree and fails when a report loses its label', () => {
  const pass = execFileSync(process.execPath, [join(ROOT, 'scripts/check-baseline-label.mjs')], { encoding: 'utf8' });
  assert.match(pass, /PASS/);
  assert.match(pass, new RegExp(BASELINE_LABEL));

  const json = JSON.parse(execFileSync(process.execPath, [join(ROOT, 'scripts/check-baseline-label.mjs'), '--json'], { encoding: 'utf8' }));
  assert.equal(json.findings.length, 0);
  assert.equal(json.checked, REPORTS.length, 'the CLI registry and this test list must agree');
});
