/**
 * The floor attribution label and the check that enforces it.
 *
 * Coord's decision (2026-10-08, bead mwg-train-6ek): we consume web-uplift's published ruleset, and
 * every floor artifact and report we generate must say 'mwg-train deterministic baseline', so nobody
 * reads our deterministic mechanical floor as an official `web-uplift` result. The pin check verifies
 * the ruleset; this verifies the attribution.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import {
  checkBaselineLabel,
  checkDocumentClassification,
  DOCUMENTS,
  EXCLUSIONS,
  falseProvenance,
  FLOOR_EVIDENCE,
  REGISTRY,
} from '../scripts/check-baseline-label.mjs';
import { FLOOR_DOCUMENTS, labelDocuments } from '../scripts/label-baseline.mjs';
import { BASELINE_FIELDS, BASELINE_LABEL, baselineAttributionLine } from '../src/eval/ruleset.mjs';

const ROOT = resolve(import.meta.dirname, '..');

// The floor report list is DERIVED, not restated. It used to be a hand-maintained array here asserted
// equal to the check's own registry, and that duplication is exactly how adding a floor report to the
// instrument's DOCUMENTS without adding it here broke this suite - a test whose failure message was
// "the expected floor reports and the classification must agree" between one list and its own copy. The
// check script is import-safe (it guards its CLI with `import.meta.url === file://argv[1]`), so the test
// imports the real registry instead of describing it.
//
// A floor on the count is what stops the derived list quietly shrinking: without it, deleting entries
// from DOCUMENTS would make every assertion below consider less while still passing.
const MINIMUM_FLOOR_REPORTS = 31;

test('every registered floor report carries the label', () => {
  for (const path of REGISTRY) {
    const text = readFileSync(join(ROOT, path), 'utf8');
    assert.ok(text.includes(BASELINE_LABEL), `${path} must carry '${BASELINE_LABEL}'`);
  }
  assert.deepEqual(checkBaselineLabel(REGISTRY), []);
});

test('the label is one string shared by every writer', () => {
  assert.equal(BASELINE_LABEL, 'mwg-train deterministic baseline');
  assert.ok(baselineAttributionLine().includes(BASELINE_LABEL));
  // The disclaimer has to name the product it is disclaiming, otherwise it does not disclaim anything.
  assert.match(baselineAttributionLine(), /web-uplift/);
  assert.match(baselineAttributionLine(), /not an official/);
});

test('a report without the label fails the check', () => {
  const dir = mkdtempSync(join(tmpdir(), 'baseline-label-'));
  try {
    const path = join(dir, 'report.md');
    writeFileSync(path, '# A floor report\n\nstructural 0.805, target 0.75\n');
    const found = checkBaselineLabel([path]);
    assert.deepEqual(found.map((f) => f.code), ['LABEL_MISSING']);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('a report that claims web-uplift authorship fails even when labelled', () => {
  const dir = mkdtempSync(join(tmpdir(), 'baseline-label-'));
  try {
    const path = join(dir, 'report.md');
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThis is an official web-uplift result.\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThe report web-uplift generated.\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // The two evasions review named: a detector that only covered 'official web-uplift result' and
    // 'web-uplift generated' let both of these pass on an otherwise labelled report.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nGenerated by web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift's official baseline\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nnumbers from web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // Second-round evasions: an authoring verb, and a negation in a DIFFERENT clause that the old
    // 24-character lookback treated as disclaiming the claim.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift built this floor\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nNot a mock; built by web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift produced these numbers\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // Authorship by noun rather than by verb, which no pattern covered.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThis floor is a web-uplift product\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThis floor is a web-uplift result\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('our own disclaimer is not mistaken for a claim', () => {
  // The label line negates the phrase it contains. A check that flagged it would fail on every report
  // it is supposed to accept, which is the fastest way to get a check deleted.
  assert.equal(falseProvenance(baselineAttributionLine()), null);
  assert.equal(falseProvenance('This is not an official web-uplift result.'), null);
  assert.equal(falseProvenance('structural 0.805'), null);
  assert.equal(falseProvenance('This is an official web-uplift result.'), 'official web-uplift');
  // A mention is not a claim: naming the product as something we compare against is legitimate, and so
  // is a true statement about THEIR artefact. Flagging those would make the check wrong about the thing
  // it is right about, which is how a check gets disabled.
  assert.equal(falseProvenance('we compare our floor against the web-uplift catalogue'), null);
  assert.equal(falseProvenance('The canonical catalog published by web-uplift changed.'), null);
  assert.equal(falseProvenance('The ruleset published by web-uplift has 178 guides.'), null);
  assert.equal(falseProvenance('We did not use web-uplift for our floor.'), null);
  // Review found this flagged as a false positive: the preposition attaches to 'rules', which are theirs,
  // so this is a true statement about where our rules came from, not a claim about our floor.
  assert.equal(falseProvenance('Our baseline uses rules from web-uplift.'), null);
  // The possessive attaches to the noun after it, so this is about their rules and not our floor.
  assert.equal(falseProvenance("Our baseline uses web-uplift's rules."), null);
  assert.equal(falseProvenance("We follow web-uplift's guides."), null);
  assert.equal(falseProvenance("We follow web-uplift's rule set."), null);
  // 'guidance' was missing from the artefact nouns, so a true statement was flagged.
  assert.equal(falseProvenance("Our baseline follows web-uplift's guidance."), null);
  // The exception applies only when the possessive ENDS at their artefact noun. Here the hyphen makes
  // 'rules' a modifier of 'baseline', so the head noun is 'baseline' - a claim about our floor that an
  // earlier version skipped because the captured word was 'rules'.
  assert.equal(falseProvenance("Our floor is web-uplift's rules-based baseline"), "web-uplift's rules");
});

test('a registered report that is missing fails rather than passing quietly', () => {
  // The registry is a claim that these reports exist and were checked. If one is gone, the claim is
  // false, and a check that skips missing files reports success having checked nothing.
  const found = checkBaselineLabel(['docs/eval/conformance/does-not-exist.md']);
  assert.deepEqual(found.map((f) => f.code), ['REPORT_MISSING']);
});

test('the provenance detector keeps its two-way contract', () => {
  // Table-driven because five rounds of review each found a wording the previous rule got wrong: a
  // hyphenation, a modifier chain, a passive, a prepositional phrase, a plural, and a preposition that was
  // not in the stop list. The obligation runs both ways - a missed attribution is unattributed provenance,
  // and a flagged true statement is a check someone turns off - so both columns are asserted, and the
  // counts are asserted too, because a comment saying "30 cases" was wrong the last time I counted by hand.
  const cases = [
    // --- Attributions to web-uplift of OUR floor or its numbers: must be caught.
    ["Our floor is web-uplift's rules-based baseline", true],
    ["Our floor is web-uplift's rules based baseline", true],
    ["Our floor is web-uplift's rule set-based baseline", true],
    ["web-uplift's rules-aligned independently verified mechanical baseline", true],
    ["web-uplift's official baseline", true],
    ["web-uplift's floor for us", true],
    ["web-uplift's baselines for our corpus", true],
    ["web-uplift's baseline measurements for our corpus", true],
    ["web-uplift's measured baselines", true],
    ["web-uplift's per-guide scores", true],
    ["web-uplift's metrics", true],
    ["web-uplift's tables for our corpus", true],
    ["web-uplift's predicted versus observed scores for our corpus", true],
    ["Our metrics come from web-uplift's runs", true],
    ["Our baseline is actually web-uplift's ruleset", true],
    ["Our baseline remains web-uplift's ruleset", true],
    ['This floor is a web-uplift product', true],
    ['This floor is a web-uplift result', true],
    ['web-uplift built this floor', true],
    ['Not a mock; built by web-uplift', true],
    ['The floor was constructed by web-uplift', true],
    ['This report was assembled by web-uplift', true],
    ['The baseline was assembled by web-uplift', true],
    ['numbers from web-uplift', true],
    // --- True statements about our own work, or about THEIR artefact: must pass.
    ["Our baseline uses web-uplift's rules.", false],
    ["Our baseline follows web-uplift's guidance.", false],
    ["We follow web-uplift's rule set.", false],
    ["Our floor uses web-uplift's rule-set", false],
    ["Our floor uses web-uplift's rules, and our baseline follows them.", false],
    ["Our floor uses web-uplift's rules for floor scores", false],
    ["Our floor follows web-uplift's published rules", false],
    ["Our baseline follows web-uplift's rules-based approach", false],
    ["Our report presents web-uplift's rules alongside independently computed floor scores", false],
    ["Their report shows web-uplift's rules alongside our own measurements", false],
    ["Our report cites web-uplift's report alongside its guide", false],
    ["Our report cites web-uplift's catalogue and our own floor scores", false],
    ["We compare our baselines with web-uplift's guides", false],
    ['Our baseline uses rules from web-uplift.', false],
    ['Our baseline is built from web-uplift rules', false],
    ['Our rules came from web-uplift.', false],
    ['Our scores came from web-uplift.', true],
    ['the conformance deltas come from web-uplift', true],
    ['The canonical catalog published by web-uplift changed.', false],
    ['The catalogue was published by web-uplift', false],
    ["The catalogue is web-uplift's", false],
    ['Guidance published by web-uplift', false],
    ['web-uplift publishes the guide set we follow', false],
    ['not an official web-uplift result', false],
    ['we compare our floor against the web-uplift catalogue', false],
  ];
  const wrong = [];
  for (const [text, shouldFlag] of cases) {
    const got = falseProvenance(text);
    if ((got !== null) !== shouldFlag) wrong.push(`${shouldFlag ? 'missed' : 'false positive'}: ${text} -> ${JSON.stringify(got)}`);
  }
  assert.deepEqual(wrong, []);
  // These two numbers are the counts at this revision, asserted so they cannot drift the way the
  // hand-written "30 cases" did. My own first attempt at them here was wrong by one, which is the point.
  assert.equal(cases.filter(([, flag]) => flag).length, 26, 'attributions that must be caught');
  assert.equal(cases.filter(([, flag]) => !flag).length, 23, 'true statements that must pass');
});

test('document coverage fails closed, not open', () => {
  // Review's counterexample: a NEW document stating a floor result in wording no pattern anticipates.
  // The earlier phrase-scan was fail-open and passed it. Coverage is now a classification: every tracked
  // document is either a floor report (which must carry the label) or a named kind, and anything else is a
  // finding - so a new document has to be decided deliberately rather than silently omitted.
  const dir = mkdtempSync(join(tmpdir(), 'floor-classify-'));
  try {
    const write = (name, body) => {
      const path = join(dir, name);
      writeFileSync(path, body);
      return path;
    };
    const unclassified = write('new-results.md', '# New results\n\nOur mechanical floor scored 0.805 overall in booking.\n');
    const found = checkDocumentClassification([unclassified]);
    assert.deepEqual(found.map((f) => f.code), ['UNCLASSIFIED_DOCUMENT']);

    // A document classified as a floor report must carry the label.
    const mislabelled = write('report.md', '# Report\n\n34 of 35 accepted pairs.\n');
    assert.deepEqual(checkDocumentClassification([mislabelled]).map((f) => f.code), ['UNCLASSIFIED_DOCUMENT']);

    // Generated trees are classified by pattern, not listed - but the pattern pins the artefact SHAPE, so a
    // new document inside one of those trees is still unclassified. Review found the earlier directory-wide
    // patterns would have exempted docs/eval/briefs/new-results.md, which is the same fail-open hole the
    // classification was introduced to close.
    const generated = [
      'docs/eval/projects/index.json',
      'docs/eval/projects/already-modern/cf-06/tree.json',
      'pilot/projects/account-recovery-hono/spec.json',
      'data/A1_self_generated/targets/tr-01/signature.json',
    ];
    for (const path of generated) {
      assert.deepEqual(checkDocumentClassification([path]), [], `${path} should be a generated artefact`);
    }
    const newInsideGenerated = [
      'docs/eval/briefs/new-results.md',
      'docs/eval/specs/new-results.json',
      'data/A6_evaluation/targets/new-results.json',
      'docs/eval/projects/already-modern/cf-06/new-results.md',
      'pilot/projects/account-recovery-hono/notes.md',
      'pilot/training-projects/tr-01/notes.md',
    ];
    for (const path of newInsideGenerated) {
      assert.deepEqual(
        checkDocumentClassification([path]).map((f) => f.code),
        ['UNCLASSIFIED_DOCUMENT'],
        `${path} must not be exempted by a directory pattern`,
      );
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('the relabel tool refuses anything that is not attribution-only', () => {
  // The guard is the point of the tool: a relabel that changed a measurement would be falsification.
  // Simulate it by pointing the tool at a document whose label fields already exist in a different form,
  // which makes the stripped comparison differ.
  const dir = mkdtempSync(join(tmpdir(), 'label-baseline-'));
  try {
    const path = join(dir, 'record.json');
    // Canonically formatted, because the byte-safety guard deliberately refuses a document it cannot
    // reproduce exactly - which is why this fixture uses the tool's own formatting.
    writeFileSync(path, `${JSON.stringify({ measured: 0.805, baseline_label: 'something else' }, null, 2)}\n`);
    const result = labelDocuments([path])[0];
    assert.equal(result.code, 'REFUSED_NOT_ATTRIBUTION_ONLY');
    assert.equal(JSON.parse(readFileSync(path, 'utf8')).baseline_label, 'something else', 'a refused write must not modify the file');

    // A clean document is labelled, and --check reports it without writing.
    const clean = join(dir, 'clean.json');
    writeFileSync(clean, `${JSON.stringify({ measured: 0.805 }, null, 2)}\n`);
    assert.equal(labelDocuments([clean], { check: true })[0].code, 'WOULD_LABEL');
    assert.equal(JSON.parse(readFileSync(clean, 'utf8')).baseline_label, undefined, '--check must not write');
    assert.equal(labelDocuments([clean])[0].code, 'LABELLED');
    assert.equal(JSON.parse(readFileSync(clean, 'utf8')).baseline_label, BASELINE_LABEL);
    assert.equal(labelDocuments([clean])[0].code, 'ALREADY_LABELLED', 'relabelling is idempotent');

    // Review's byte-safety counterexample: JSON.parse rounds 9007199254740993 to ...992, so a guard that
    // only compares parsed documents would rewrite a measurement and report success. Refused instead.
    const big = join(dir, 'big.json');
    const original = '{"measured":9007199254740993}';
    writeFileSync(big, original);
    assert.equal(labelDocuments([big])[0].code, 'REFUSED_NOT_BYTE_SAFE');
    assert.equal(readFileSync(big, 'utf8'), original, 'a refused document must not be touched');

    // Byte-safety, not string-safety: an invalid UTF-8 byte inside a string decodes to U+FFFD, so a
    // string comparison passes while writing re-encodes it as EF BF BD and changes the file.
    const badUtf8 = join(dir, 'bad-utf8.json');
    const bytes = Buffer.concat([Buffer.from('{"a":"'), Buffer.from([0xff]), Buffer.from('"}')]);
    writeFileSync(badUtf8, bytes);
    assert.equal(labelDocuments([badUtf8])[0].code, 'REFUSED_NOT_BYTE_SAFE');
    assert.ok(readFileSync(badUtf8).equals(bytes), 'a refused document must keep its exact bytes');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('the derived registry is a real floor, not an empty list that trivially passes', () => {
  // Replaces a test that compared the registry with a hand-written copy of itself. The property worth
  // asserting is that the derived list is still the size it was, so entries cannot quietly disappear from
  // the classification and leave every other assertion here checking less.
  assert.ok(
    REGISTRY.length >= MINIMUM_FLOOR_REPORTS,
    `the derived floor report registry has shrunk to ${REGISTRY.length}, below the ${MINIMUM_FLOOR_REPORTS} it had: a floor report has lost its classification`,
  );
  assert.ok(REGISTRY.every((path) => typeof path === 'string' && path.length > 0), 'every entry is a path');
});

test('the CLI passes on the tree and fails when a report loses its label', () => {
  const pass = execFileSync(process.execPath, [join(ROOT, 'scripts/check-baseline-label.mjs')], { encoding: 'utf8' });
  assert.match(pass, /PASS/);
  assert.match(pass, new RegExp(BASELINE_LABEL));

  const json = JSON.parse(execFileSync(process.execPath, [join(ROOT, 'scripts/check-baseline-label.mjs'), '--json'], { encoding: 'utf8' }));
  assert.equal(json.findings.length, 0);
  assert.equal(json.checked, REGISTRY.length, 'the CLI registry and the derived registry must agree');
  assert.ok(json.checked >= MINIMUM_FLOOR_REPORTS, 'the CLI must still be checking at least the floor');
});

// -----------------------------------------------------------------------------------------------------------
// Quoted paths. git C-quotes any tracked path containing a character it considers unusual (core.quotePath
// defaults to true), so a newline-split enumeration returns "pilot/projects/t\303\253st/package.json" for a file
// really named pilot/projects/tëst/package.json. That quoted string matches no DOCUMENTS key and no
// GENERATED_PATTERN, so a correctly classified or generated document was reported UNCLASSIFIED_DOCUMENT.
// The check now enumerates with `git ls-files -z` and splits on NUL, which never appears in a path.
test('a path git would quote still classifies, because enumeration is NUL-separated', async () => {
  const { execFileSync } = await import('node:child_process');
  const { mkdtempSync, mkdirSync, writeFileSync, rmSync } = await import('node:fs');
  const { tmpdir } = await import('node:os');
  const { join } = await import('node:path');
  const { listTrackedDocuments, checkDocumentClassification, GENERATED_PATTERNS } = await import('../scripts/check-baseline-label.mjs');

  const dir = mkdtempSync(join(tmpdir(), 'dby-'));
  try {
    execFileSync('git', ['init', '-q', '.'], { cwd: dir });
    // The non-ASCII directory name is what makes git quote the path, and package.json is a generated pattern.
    const relative = join('pilot', 'projects', 'tëst-01', 'package.json');
    mkdirSync(join(dir, 'pilot', 'projects', 'tëst-01'), { recursive: true });
    writeFileSync(join(dir, relative), '{"name":"probe"}');
    execFileSync('git', ['add', '-A'], { cwd: dir });

    // The old enumeration form, so the defect is pinned as a fact rather than described: git hands back a quoted
    // string, which is why the pattern cannot match it.
    const quoted = execFileSync('git', ['ls-files', '*.md', '*.json'], { cwd: dir, encoding: 'utf8' }).trim();
    assert.notEqual(quoted, 'pilot/projects/tëst-01/package.json', 'git still quotes this path');
    assert.ok(!GENERATED_PATTERNS.some((pattern) => pattern.test(quoted)), 'the quoted form matches no pattern, which was the bug');

    // The defect's EFFECT, asserted here rather than only described in a commit message: classified through the
    // old quoted path, the document comes back as an UNCLASSIFIED finding. An independent review caught that an
    // earlier message claimed this assertion existed in the test while the test stopped one step short of it.
    const asReportedBefore = checkDocumentClassification([quoted]);
    assert.equal(asReportedBefore.length, 1, 'the quoted path is exactly one false finding');
    assert.equal(asReportedBefore[0].code, 'UNCLASSIFIED_DOCUMENT');

    // The fix: enumerate from the repository, and the real path classifies with no findings.
    const tracked = listTrackedDocuments({ cwd: dir });
    assert.ok(tracked.includes('pilot/projects/tëst-01/package.json'), `unquoted path expected, saw ${JSON.stringify(tracked)}`);
    assert.deepEqual(checkDocumentClassification(tracked), [], 'a generated document must not be reported UNCLASSIFIED');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('a character counter is a known intentional trigger, and rewording is the remedy', () => {
  // Coord's ruling, 2026-10-08, bead mwg-train-e1c: do NOT loosen FLOOR_EVIDENCE. The bare digit-slash-digit
  // branch has no context on purpose, so a live counter like `0/500` matches it and a design-labelled
  // document containing one is reported. That is the accepted cost of failing CLOSED - the other direction,
  // missing a document that quotes a floor measurement, is the failure that shipped four times.
  //
  // Measured, because the obvious remedies do not actually work and it is worth having that written down:
  // a denominator threshold cannot separate a counter from `91/135` or `36/142`, which are real pair counts.

  // 1. THE TRIGGER IS INTENTIONAL, not an accident to be tidied away.
  assert.ok(
    FLOOR_EVIDENCE.test('The message field is capped at 500 characters, showing 0/500 as you type.'),
    'a bare fraction is a known trigger and must stay one',
  );

  // 2. THE REMEDY COORD NAMED, measured against the real pattern rather than assumed.
  for (const remedy of ['0 of 500', '0 / 500 max', 'capped at 500 characters']) {
    assert.equal(FLOOR_EVIDENCE.test(remedy), false, `${JSON.stringify(remedy)} must pass, or the remedy is not a remedy`);
  }

  // 3. AND THE BRANCH STILL DOES ITS REAL JOB: any threshold that excluded 0/500 by size would also lose
  // these, which is why the remedy is rewording rather than narrowing.
  for (const real of ['7/7', '91/135', '40/40', '29/29', '36/142']) {
    assert.ok(FLOOR_EVIDENCE.test(real), `${real} is genuine floor evidence and must keep matching`);
  }

  // 4. END TO END, through the classification check, so this is the behaviour and not just the regex.
  const dir = mkdtempSync(join(tmpdir(), 'e1c-counter-'));
  const path = join(dir, 'counter.md');
  DOCUMENTS[path] = 'design';
  try {
    writeFileSync(path, '# Demo\n\nThe message field is capped at 500 characters, showing 0/500 as you type.\n');
    assert.deepEqual(
      checkDocumentClassification([path]).map((finding) => finding.code),
      ['MISCLASSIFIED_DOCUMENT'],
      'a design document with a live counter is flagged, deliberately',
    );
    writeFileSync(path, '# Demo\n\nThe message field is capped at 500 characters, showing 0 of 500 as you type.\n');
    assert.deepEqual(
      checkDocumentClassification([path]).map((finding) => finding.code),
      [],
      'and the reworded counter passes, which is the documented remedy',
    );
  } finally {
    delete DOCUMENTS[path];
    rmSync(dir, { recursive: true, force: true });
  }
});

// -----------------------------------------------------------------------------------------------------------
// The labeler's own --check, which is the half that was NOT covered. check:baseline-label was tested and
// green while `label:baseline --check` was red on main for two committed documents, because nothing ran
// the labeler's check against the tree. Two gates guard the same decision and only one was watched.
//
// mwg-train-jjl: docs/train/corpus/records.json carried baseline_label and baseline_tool but not
// baseline_definition, and docs/train/corpus/tokens.json carried none of the three.
test('the labeler --check is clean on the committed tree, for every declared floor document', () => {
  const results = labelDocuments(FLOOR_DOCUMENTS, { check: true });
  const refused = results.filter((r) =>
    ['UNREADABLE', 'REFUSED_NOT_ATTRIBUTION_ONLY', 'REFUSED_NOT_BYTE_SAFE'].includes(r.code),
  );
  assert.deepEqual(refused, [], 'no declared document may be unwritable or unsafe to label');
  const pending = results.filter((r) => r.code === 'WOULD_LABEL').map((r) => r.path);
  assert.deepEqual(pending, [], `these documents state a floor without the attribution: ${pending.join(', ')}`);
  // The check above only proves the label is ABSENT or present as a whole; assert the exact fields, so a
  // document carrying two of the three cannot pass. That is the precise defect this bead describes.
  for (const path of FLOOR_DOCUMENTS) {
    const document = JSON.parse(readFileSync(join(ROOT, path), 'utf8'));
    for (const [key, value] of Object.entries(BASELINE_FIELDS)) {
      assert.equal(document[key], value, `${path} must carry ${key}`);
    }
  }
});

test('the tokens generator writes the attribution into the document it produces', async () => {
  const { writeTokensJson } = await import('../scripts/train-corpus-tokens.mjs');
  const dir = mkdtempSync(join(tmpdir(), 'mwg-tokens-'));
  try {
    const out = join(dir, 'tokens.json');
    // The tool only adds the canonical fields in its structured branch, which it takes when the output is
    // the canonical path or an existing file with sections - so seed one, or this would exercise the
    // standalone /tmp branch instead and prove nothing.
    writeFileSync(out, JSON.stringify({ $comment: 'seeded', pilot: null, training: null }));
    writeTokensJson(out, 'training', { total_training_tokens: 1234, families: [] }, {});
    const written = JSON.parse(readFileSync(out, 'utf8'));
    for (const [key, value] of Object.entries(BASELINE_FIELDS)) {
      assert.equal(written[key], value, `the generated tokens document must carry ${key}`);
    }
    assert.equal(written.training.total_training_tokens, 1234, 'the measurement must survive the labelling');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('relabelling a record that carries only some fields adds the rest and touches no measurement', async () => {
  const { relabelRecord } = await import('../scripts/train-corpus-run.mjs');
  const dir = mkdtempSync(join(tmpdir(), 'mwg-relabel-'));
  try {
    const path = join(dir, 'records.json');
    // The exact shape that was committed: the label and the tool, but no definition - which is why
    // `label:baseline --check` reported WOULD_LABEL for a document that looked labelled.
    const record = {
      run_id: 'run-1',
      baseline_label: BASELINE_LABEL,
      baseline_tool: 'src/corpus/uplift.mjs',
      generated_at: '2026-01-01T00:00:00.000Z',
      summary: { accepted: 1, attempted: 2 },
      projects: [
        { id: 'p1', decision: { accepted: true, baseline_label: BASELINE_LABEL, baseline_tool: 'src/corpus/uplift.mjs' } },
      ],
    };
    writeFileSync(path, `${JSON.stringify(record, null, 2)}\n`);
    relabelRecord(path);
    const after = JSON.parse(readFileSync(path, 'utf8'));
    for (const [key, value] of Object.entries(BASELINE_FIELDS)) {
      assert.equal(after[key], value, `the record must carry ${key} after relabelling`);
      assert.equal(after.projects[0].decision[key], value, `the decision must carry ${key} after relabelling`);
    }
    assert.deepEqual(after.summary, record.summary, 'no measured field may change');
    assert.equal(after.projects[0].decision.accepted, true, 'no measured field may change');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
