/**
 * The floor attribution label and the check that enforces it.
 *
 * Coord's decision (2026-10-08, bead mwg-train-6ek): we consume web-uplift's published ruleset, and
 * every floor artifact and report we generate must say 'mwg-train deterministic baseline', so nobody
 * reads our deterministic mechanical floor as an official `web-uplift` result. The pin check verifies
 * the ruleset; this verifies the attribution.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { checkBaselineLabel, discoverUnlabelledFloorEvidence, EXCLUSIONS, falseProvenance } from '../scripts/check-baseline-label.mjs';
import { labelDocuments } from '../scripts/label-baseline.mjs';
import { BASELINE_LABEL, baselineAttributionLine } from '../src/eval/ruleset.mjs';

const ROOT = resolve(import.meta.dirname, '..');

// The registry lives in the check script; importing it would run the CLI, so the reports are listed
// here as well. If a report is added to one list and not the other this test still passes, so the
// CLI test below covers the registry as a whole.
const REPORTS = [
  'docs/eval/conformance/booking.md',
  'docs/eval/conformance/account-recovery-identity.md',
  'docs/eval/conformance/booking-identity.md',
  'docs/eval/conformance/catalogue-identity.md',
  'docs/eval/conformance/contact-lead-identity.md',
  'docs/eval/conformance/event-registration-identity.md',
  'docs/pilot/YIELD.md',
  'docs/train/corpus/YIELD.md',
  'docs/train/corpus/records.json',
  'pilot/CORPUS.json',
  'docs/pilot/yield.json',
  'docs/pilot/records.json',
  'docs/eval/conformance/booking.json',
  'docs/eval/conformance/account-recovery-identity.json',
  'docs/eval/conformance/booking-identity.json',
  'docs/eval/conformance/catalogue-identity.json',
  'docs/eval/conformance/contact-lead-identity.json',
  'docs/eval/conformance/event-registration-identity.json',
  'docs/pilot/README.md',
  'docs/eval/conformance/README.md',
  'docs/train/corpus/tokens.json',
  'docs/train/corpus/README.md',
  'docs/eval/two-backends.md',
];

test('every registered floor report carries the label', () => {
  for (const path of REPORTS) {
    const text = readFileSync(join(ROOT, path), 'utf8');
    assert.ok(text.includes(BASELINE_LABEL), `${path} must carry '${BASELINE_LABEL}'`);
  }
  assert.deepEqual(checkBaselineLabel(REPORTS), []);
});

test('the label is one string shared by every writer', () => {
  assert.equal(BASELINE_LABEL, 'mwg-train deterministic baseline');
  assert.ok(baselineAttributionLine().includes(BASELINE_LABEL));
  // The disclaimer has to name the product it is disclaiming, otherwise it does not disclaim anything.
  assert.match(baselineAttributionLine(), /web-uplift/);
  assert.match(baselineAttributionLine(), /not an official/);
});

test('a report without the label fails the check', () => {
  const dir = mkdtempSync(join(tmpdir(), 'baseline-label-'));
  try {
    const path = join(dir, 'report.md');
    writeFileSync(path, '# A floor report\n\nstructural 0.805, target 0.75\n');
    const found = checkBaselineLabel([path]);
    assert.deepEqual(found.map((f) => f.code), ['LABEL_MISSING']);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('a report that claims web-uplift authorship fails even when labelled', () => {
  const dir = mkdtempSync(join(tmpdir(), 'baseline-label-'));
  try {
    const path = join(dir, 'report.md');
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThis is an official web-uplift result.\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThe report web-uplift generated.\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // The two evasions review named: a detector that only covered 'official web-uplift result' and
    // 'web-uplift generated' let both of these pass on an otherwise labelled report.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nGenerated by web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift's official baseline\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nnumbers from web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // Second-round evasions: an authoring verb, and a negation in a DIFFERENT clause that the old
    // 24-character lookback treated as disclaiming the claim.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift built this floor\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nNot a mock; built by web-uplift\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nweb-uplift produced these numbers\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);

    // Authorship by noun rather than by verb, which no pattern covered.
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThis floor is a web-uplift product\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
    writeFileSync(path, `# Report\n\n${baselineAttributionLine()}\n\nThis floor is a web-uplift result\n`);
    assert.deepEqual(checkBaselineLabel([path]).map((f) => f.code), ['FALSE_PROVENANCE']);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('our own disclaimer is not mistaken for a claim', () => {
  // The label line negates the phrase it contains. A check that flagged it would fail on every report
  // it is supposed to accept, which is the fastest way to get a check deleted.
  assert.equal(falseProvenance(baselineAttributionLine()), null);
  assert.equal(falseProvenance('This is not an official web-uplift result.'), null);
  assert.equal(falseProvenance('structural 0.805'), null);
  assert.equal(falseProvenance('This is an official web-uplift result.'), 'official web-uplift');
  // A mention is not a claim: naming the product as something we compare against is legitimate, and so
  // is a true statement about THEIR artefact. Flagging those would make the check wrong about the thing
  // it is right about, which is how a check gets disabled.
  assert.equal(falseProvenance('we compare our floor against the web-uplift catalogue'), null);
  assert.equal(falseProvenance('The canonical catalog published by web-uplift changed.'), null);
  assert.equal(falseProvenance('The ruleset published by web-uplift has 178 guides.'), null);
  assert.equal(falseProvenance('We did not use web-uplift for our floor.'), null);
  // Review found this flagged as a false positive: the preposition attaches to 'rules', which are theirs,
  // so this is a true statement about where our rules came from, not a claim about our floor.
  assert.equal(falseProvenance('Our baseline uses rules from web-uplift.'), null);
  // The possessive attaches to the noun after it, so this is about their rules and not our floor.
  assert.equal(falseProvenance("Our baseline uses web-uplift's rules."), null);
  assert.equal(falseProvenance("We follow web-uplift's guides."), null);
  assert.equal(falseProvenance("We follow web-uplift's rule set."), null);
  // 'guidance' was missing from the artefact nouns, so a true statement was flagged.
  assert.equal(falseProvenance("Our baseline follows web-uplift's guidance."), null);
  // The exception applies only when the possessive ENDS at their artefact noun. Here the hyphen makes
  // 'rules' a modifier of 'baseline', so the head noun is 'baseline' - a claim about our floor that an
  // earlier version skipped because the captured word was 'rules'.
  assert.equal(falseProvenance("Our floor is web-uplift's rules-based baseline"), "web-uplift's rules");
});

test('a registered report that is missing fails rather than passing quietly', () => {
  // The registry is a claim that these reports exist and were checked. If one is gone, the claim is
  // false, and a check that skips missing files reports success having checked nothing.
  const found = checkBaselineLabel(['docs/eval/conformance/does-not-exist.md']);
  assert.deepEqual(found.map((f) => f.code), ['REPORT_MISSING']);
});

test('the provenance detector keeps its two-way contract', () => {
  // Table-driven because this is the fourth round in which a wording slipped through: a hyphenation, a
  // modifier chain, a passive, and a prepositional phrase were each missed or wrongly flagged by the
  // previous rule. The obligation runs both ways - a missed attribution is unattributed provenance, and a
  // flagged true statement is a check someone turns off - so both columns are asserted, and the counts
  // are asserted too, because a comment saying "30 cases" was wrong the last time I wrote one by hand.
  const cases = [
    // --- Attributions to web-uplift of OUR floor or its numbers: must be caught.
    ["Our floor is web-uplift's rules-based baseline", true],
    ["Our floor is web-uplift's rules based baseline", true],
    ["Our floor is web-uplift's rule set-based baseline", true],
    ["web-uplift's rules-aligned independently verified mechanical baseline", true],
    ["web-uplift's official baseline", true],
    ["web-uplift's floor for us", true],
    ["Our baseline is actually web-uplift's ruleset", true],
    ["Our baseline remains web-uplift's ruleset", true],
    ['This floor is a web-uplift product', true],
    ['This floor is a web-uplift result', true],
    ['web-uplift built this floor', true],
    ['Not a mock; built by web-uplift', true],
    ['The floor was constructed by web-uplift', true],
    ['This report was assembled by web-uplift', true],
    ['The baseline was assembled by web-uplift', true],
    ['numbers from web-uplift', true],
    ['Our scores came from web-uplift.', true],
    ['the conformance deltas come from web-uplift', true],
    // --- True statements about our own work, or about THEIR artefact: must pass.
    ["Our baseline uses web-uplift's rules.", false],
    ["Our baseline follows web-uplift's guidance.", false],
    ["We follow web-uplift's rule set.", false],
    ["Our floor uses web-uplift's rule-set", false],
    ["Our floor uses web-uplift's rules, and our baseline follows them.", false],
    ["Our floor uses web-uplift's rules for floor scores", false],
    ["Our floor follows web-uplift's published rules", false],
    ["Our baseline follows web-uplift's rules-based approach", false],
    ['Our baseline uses rules from web-uplift.', false],
    ['Our baseline is built from web-uplift rules', false],
    ['Our rules came from web-uplift.', false],
    ['The canonical catalog published by web-uplift changed.', false],
    ['The catalogue was published by web-uplift', false],
    ["The catalogue is web-uplift's", false],
    ['Guidance published by web-uplift', false],
    ['web-uplift publishes the guide set we follow', false],
    ['not an official web-uplift result', false],
    ['we compare our floor against the web-uplift catalogue', false],
  ];
  const wrong = [];
  for (const [text, shouldFlag] of cases) {
    const got = falseProvenance(text);
    if ((got !== null) !== shouldFlag) wrong.push(`${shouldFlag ? 'missed' : 'false positive'}: ${text} -> ${JSON.stringify(got)}`);
  }
  assert.deepEqual(wrong, []);
  assert.equal(cases.filter(([, flag]) => flag).length, 18, 'attributions that must be caught');
  assert.equal(cases.filter(([, flag]) => !flag).length, 18, 'true statements that must pass');
});

test('the scan finds floor evidence the registry does not list', () => {
  // This is the structural fix for a finding that returned four times: a list can only cover what its
  // author thought of, so coverage is now discovered from the tree rather than asserted from memory.
  const dir = mkdtempSync(join(tmpdir(), 'floor-scan-'));
  try {
    const write = (name, body) => {
      const path = join(dir, name);
      writeFileSync(path, body);
      return path;
    };
    const unlabelled = write('report.md', '# Report\n\n34 of 35 accepted pairs.\n');
    const labelled = write('labelled.md', `# Report\n\n${baselineAttributionLine()}\n\n34 of 35 accepted pairs.\n`);
    const unrelated = write('other.md', '# Notes\n\nNothing measured here.\n');

    const found = discoverUnlabelledFloorEvidence([unlabelled, labelled, unrelated]);
    assert.deepEqual(found.map((f) => f.subject), [unlabelled]);
    assert.equal(found[0].code, 'UNLABELLED_FLOOR_EVIDENCE');

    // Excluded by name, and generated trees, are not reports and must not be scanned.
    assert.deepEqual(discoverUnlabelledFloorEvidence([Object.keys(EXCLUSIONS)[0]]), []);
    assert.deepEqual(discoverUnlabelledFloorEvidence(['pilot/projects/tr-01-hono/spec.json']), []);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('the relabel tool refuses anything that is not attribution-only', () => {
  // The guard is the point of the tool: a relabel that changed a measurement would be falsification.
  // Simulate it by pointing the tool at a document whose label fields already exist in a different form,
  // which makes the stripped comparison differ.
  const dir = mkdtempSync(join(tmpdir(), 'label-baseline-'));
  try {
    const path = join(dir, 'record.json');
    // Canonically formatted, because the byte-safety guard deliberately refuses a document it cannot
    // reproduce exactly - which is why this fixture uses the tool's own formatting.
    writeFileSync(path, `${JSON.stringify({ measured: 0.805, baseline_label: 'something else' }, null, 2)}\n`);
    const result = labelDocuments([path])[0];
    assert.equal(result.code, 'REFUSED_NOT_ATTRIBUTION_ONLY');
    assert.equal(JSON.parse(readFileSync(path, 'utf8')).baseline_label, 'something else', 'a refused write must not modify the file');

    // A clean document is labelled, and --check reports it without writing.
    const clean = join(dir, 'clean.json');
    writeFileSync(clean, `${JSON.stringify({ measured: 0.805 }, null, 2)}\n`);
    assert.equal(labelDocuments([clean], { check: true })[0].code, 'WOULD_LABEL');
    assert.equal(JSON.parse(readFileSync(clean, 'utf8')).baseline_label, undefined, '--check must not write');
    assert.equal(labelDocuments([clean])[0].code, 'LABELLED');
    assert.equal(JSON.parse(readFileSync(clean, 'utf8')).baseline_label, BASELINE_LABEL);
    assert.equal(labelDocuments([clean])[0].code, 'ALREADY_LABELLED', 'relabelling is idempotent');

    // Review's byte-safety counterexample: JSON.parse rounds 9007199254740993 to ...992, so a guard that
    // only compares parsed documents would rewrite a measurement and report success. Refused instead.
    const big = join(dir, 'big.json');
    const original = '{"measured":9007199254740993}';
    writeFileSync(big, original);
    assert.equal(labelDocuments([big])[0].code, 'REFUSED_NOT_BYTE_SAFE');
    assert.equal(readFileSync(big, 'utf8'), original, 'a refused document must not be touched');

    // Byte-safety, not string-safety: an invalid UTF-8 byte inside a string decodes to U+FFFD, so a
    // string comparison passes while writing re-encodes it as EF BF BD and changes the file.
    const badUtf8 = join(dir, 'bad-utf8.json');
    const bytes = Buffer.concat([Buffer.from('{"a":"'), Buffer.from([0xff]), Buffer.from('"}')]);
    writeFileSync(badUtf8, bytes);
    assert.equal(labelDocuments([badUtf8])[0].code, 'REFUSED_NOT_BYTE_SAFE');
    assert.ok(readFileSync(badUtf8).equals(bytes), 'a refused document must keep its exact bytes');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('the CLI passes on the tree and fails when a report loses its label', () => {
  const pass = execFileSync(process.execPath, [join(ROOT, 'scripts/check-baseline-label.mjs')], { encoding: 'utf8' });
  assert.match(pass, /PASS/);
  assert.match(pass, new RegExp(BASELINE_LABEL));

  const json = JSON.parse(execFileSync(process.execPath, [join(ROOT, 'scripts/check-baseline-label.mjs'), '--json'], { encoding: 'utf8' }));
  assert.equal(json.findings.length, 0);
  assert.equal(json.checked, REPORTS.length, 'the CLI registry and this test list must agree');
});
