/**
 * Owner-auth scan tests: the corpus rule that no owner-identifying material may appear in a site.
 * Fail-closed behaviour is tested as strictly as detection: a scan that cannot run is a refusal.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { buildMatchers, loadScanConfig, scanPair, scanRecordFiles, scanTree, ScanConfigError } from '../src/viewer/owner-auth.mjs';

const CONFIG_PATH = new URL('../docs/eval/owner-identity.json', import.meta.url).pathname;

function makeTree(files) {
  const dir = mkdtempSync(join(tmpdir(), 'owner-auth-test-'));
  for (const [name, content] of Object.entries(files)) {
    const path = join(dir, name);
    mkdirSync(join(path, '..'), { recursive: true });
    writeFileSync(path, content);
  }
  return dir;
}

test('the shipped config loads and compiles', () => {
  const config = loadScanConfig(CONFIG_PATH);
  assert.ok(config.owner_identifiers.length > 0, 'the config must list at least one owner identifier');
  buildMatchers(config);
});

test('a clean tree passes', () => {
  const dir = makeTree({ 'index.html': '<html><body>Hello</body></html>', 'server.mjs': 'createServer()' });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config));
  assert.equal(result.status, 'PASS');
  assert.deepEqual(result.findings, []);
  rmSync(dir, { recursive: true, force: true });
});

test('the owner handle is detected, case-insensitively', () => {
  const dir = makeTree({ 'README.md': 'generated by PaulKinlan tooling' });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config));
  assert.equal(result.status, 'FAIL');
  assert.equal(result.findings[0].file, 'README.md');
  assert.match(result.findings[0].patternId, /owner-identifier/);
  rmSync(dir, { recursive: true, force: true });
});

test('credential env names and token shapes are detected', () => {
  const dir = makeTree({
    'a.mjs': 'const t = process.env.GITHUB_TOKEN;',
    'b.mjs': 'const k = "github_pat_11ABCDEFG0123456789abcdef";',
  });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config));
  assert.equal(result.status, 'FAIL');
  const kinds = new Set(result.findings.map((finding) => finding.kind));
  assert.ok(kinds.has('credential-env-name'));
  assert.ok(kinds.has('token-pattern'));
  rmSync(dir, { recursive: true, force: true });
});

test('findings never contain the matched text', () => {
  const secret = 'github_pat_11ABCDEFG0123456789abcdefXYZ';
  const dir = makeTree({ 'leak.mjs': `const k = "${secret}";` });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config));
  assert.equal(result.status, 'FAIL');
  const serialised = JSON.stringify(result.findings);
  assert.ok(!serialised.includes(secret), 'the finding must not carry the secret value');
  rmSync(dir, { recursive: true, force: true });
});

test('synthetic demo auth is NOT flagged: fake users and session code are wanted features', () => {
  const dir = makeTree({
    'server.mjs': `
      const users = { 'ada@example.test': { password: 'correct horse', name: 'Ada' } };
      // demo login: synthetic accounts only
      response.writeHead(200, { 'set-cookie': 'session=' + randomUUID() });
    `,
  });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config));
  assert.equal(result.status, 'PASS', JSON.stringify(result.findings));
  rmSync(dir, { recursive: true, force: true });
});

test('fail-closed: a missing config is an ERROR and the pair is not accepted', () => {
  const dir = makeTree({ 'index.html': '<html></html>' });
  const result = scanPair({ originalDir: dir, upliftedDir: dir, configPath: '/nonexistent/owner-identity.json' });
  assert.equal(result.status, 'ERROR');
  assert.match(result.reason, /missing/);
  rmSync(dir, { recursive: true, force: true });
});

test('fail-closed: an invalid config is an ERROR', () => {
  const badConfig = makeTree({ 'bad.json': '{"owner_identifiers": "not-an-array"}' });
  const result = scanPair({
    originalDir: makeTree({ 'a.txt': 'x' }),
    upliftedDir: makeTree({ 'b.txt': 'y' }),
    configPath: join(badConfig, 'bad.json'),
  });
  assert.equal(result.status, 'ERROR');
  rmSync(badConfig, { recursive: true, force: true });
});

test('fail-closed: a missing tree fails the pair', () => {
  const dir = makeTree({ 'index.html': '<html></html>' });
  const result = scanPair({ originalDir: dir, upliftedDir: '/nonexistent/tree', configPath: CONFIG_PATH });
  assert.equal(result.status, 'FAIL');
  rmSync(dir, { recursive: true, force: true });
});

test('loadScanConfig rejects unparseable JSON as a ScanConfigError', () => {
  const dir = makeTree({ 'bad.json': 'not json{' });
  assert.throws(() => loadScanConfig(join(dir, 'bad.json')), ScanConfigError);
  rmSync(dir, { recursive: true, force: true });
});

test('proxy headers and endpoints are detected', () => {
  const dir = makeTree({
    'proxy-aware.mjs': 'const user = req.headers["x-auth-request-user"]; const p = "http://127.0.0.1:9999/github";',
  });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config));
  assert.equal(result.status, 'FAIL');
  const ids = result.findings.map((finding) => finding.patternId);
  assert.ok(ids.some((id) => id.includes('proxy-header-name')));
  assert.ok(ids.some((id) => id.includes('proxy-endpoint')));
  rmSync(dir, { recursive: true, force: true });
});

test('finding ids are opaque: they never contain the matched identifier (review finding)', () => {
  const dir = makeTree({ 'leak.md': 'contact paulkinlan for details' });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config));
  assert.equal(result.status, 'FAIL');
  for (const finding of result.findings) {
    assert.ok(!finding.patternId.includes('paulkinlan'), `pattern id leaked the identifier: ${finding.patternId}`);
  }
  rmSync(dir, { recursive: true, force: true });
});

test('config validation rejects non-string entries and empty literal sets (fail-closed)', () => {
  const bad1 = makeTree({ 'c.json': JSON.stringify({ owner_identifiers: [42], credential_env_names: [], proxy_header_names: [], proxy_endpoints: [], token_patterns: [] }) });
  assert.throws(() => loadScanConfig(join(bad1, 'c.json')), ScanConfigError);
  const bad2 = makeTree({ 'c.json': JSON.stringify({ owner_identifiers: [], credential_env_names: [], proxy_header_names: [], proxy_endpoints: [], token_patterns: [] }) });
  assert.throws(() => loadScanConfig(join(bad2, 'c.json')), /no literal patterns/);
  rmSync(bad1, { recursive: true, force: true });
  rmSync(bad2, { recursive: true, force: true });
});

test('the snake_case scan options in the shipped config are honoured', () => {
  // skip_extensions must actually skip: a planted identifier inside a .png is not a finding.
  const dir = makeTree({ 'shot.png': 'paulkinlan', 'index.html': 'hello' });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanTree(dir, buildMatchers(config), config.scan);
  assert.equal(result.status, 'PASS', JSON.stringify(result.findings));
  rmSync(dir, { recursive: true, force: true });
});

test('corpus records are scanned too: a decision record embedding the owner fails the pair', () => {
  const dir = makeTree({ 'decision.json': JSON.stringify({ project_id: 'x', note: 'uplift by paulkinlan' }) });
  const config = loadScanConfig(CONFIG_PATH);
  const result = scanRecordFiles([join(dir, 'decision.json')], buildMatchers(config), config.scan);
  assert.equal(result.status, 'FAIL');
  const clean = makeTree({ 'decision.json': JSON.stringify({ project_id: 'x' }) });
  assert.equal(scanRecordFiles([join(clean, 'decision.json'), join(clean, 'absent.json')], buildMatchers(config), config.scan).status, 'PASS');
  rmSync(dir, { recursive: true, force: true });
  rmSync(clean, { recursive: true, force: true });
});
