/**
 * Corpus discovery for the viewer.
 *
 * The corpus layout the viewer reads (produced by the pilot, bead mwg-train-sk1):
 *
 *   <corpus>/CORPUS.json                        the committed record: run id, per-project SHAs,
 *                                               acceptance, improved rules (sk1's landed design:
 *                                               the trees are re-derived, not committed)
 *   <corpus>/projects/<project_id>/spec.json
 *   <corpus>/projects/<project_id>/...            (the original tree, regenerated by the plan)
 *   <corpus>/out/<run_id>/yield.json             run records, present only where a run executed
 *   <corpus>/out/<run_id>/<project_id>/decision.json    locally (gitignored)
 *   <corpus>/out/<run_id>/<project_id>/original.json
 *   <corpus>/out/<run_id>/<project_id>/uplifted.json
 *   <corpus>/out/<run_id>/<project_id>/evidence/*.png|*.json
 *   <repo>/.pilot-uplifted/<run_id>/<project_id>/...   (kept uplifted trees, also local-only)
 *   <repo>/.pilot-uplifted/<run_id>/<project_id>/...   (uplifted trees, kept runs; an earlier
    *   layout used <corpus>/out/<run_id>/uplifted/<project_id> - both are discovered)
 *
 * The viewer never invents state: a project with no run record is shown as "no run recorded", a
 * missing record field is shown as absent, and a reject is rendered with the same prominence as an
 * accept. Acceptance bias is only inspectable if the rejects are as visible as the winners.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

/** List run ids, newest first (run ids are ISO timestamps, so lexical order is chronological). */
export function listRuns(corpusRoot) {
  const outDir = join(corpusRoot, 'out');
  if (!existsSync(outDir)) return [];
  return readdirSync(outDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .reverse();
}

/**
 * Load the corpus view for one run (or all projects without a run). Returns:
 * { runId, runs, projects: [ { id, spec, decision, original, uplifted, evidenceDir, runDir,
 *   upliftedTreeDir } ], yieldReport }
 */
export function loadCorpus(corpusRoot, runId = null) {
  const projectsRoot = join(corpusRoot, 'projects');
  const runs = listRuns(corpusRoot);
  // The manifest's recorded run is the default view, not the newest local run dir: the manifest
  // is the corpus record of record, and a newer local run without decisions must not silently
  // turn every recorded project into an unpaired one (which would serve unverified trees).
  const corpusManifest = readJson(join(corpusRoot, 'CORPUS.json'));
  const selectedRun = runId ?? corpusManifest?.run_id ?? runs[0] ?? null;
  const runDir = selectedRun && existsSync(join(corpusRoot, 'out', selectedRun)) ? join(corpusRoot, 'out', selectedRun) : null;

  const projectIds = existsSync(projectsRoot)
    ? readdirSync(projectsRoot, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort()
    : [];

  const projects = [];
  for (const id of projectIds) {
    const projectDir = join(projectsRoot, id);
    const spec = readJson(join(projectDir, 'spec.json'));
    const projectRunDir = runDir && existsSync(join(runDir, id)) ? join(runDir, id) : null;
    const decision = projectRunDir ? readJson(join(projectRunDir, 'decision.json')) : null;
    const original = projectRunDir ? readJson(join(projectRunDir, 'original.json')) : null;
    const uplifted = projectRunDir ? readJson(join(projectRunDir, 'uplifted.json')) : null;
    // Uplifted trees: the pilot keeps them at <repo>/.pilot-uplifted/<runId>/<id> (the corpus root
    // is usually <repo>/pilot); an earlier layout put them under the run dir. Check both.
    const siblingUplifted = runDir ? join(dirname(corpusRoot), '.pilot-uplifted', selectedRun, id) : null;
    const legacyUplifted = runDir ? join(runDir, 'uplifted', id) : null;
    const upliftedTreeDir =
      (siblingUplifted && existsSync(siblingUplifted) && siblingUplifted) ||
      (legacyUplifted && existsSync(legacyUplifted) && legacyUplifted) ||
      null;
    projects.push({
      id,
      spec,
      decision,
      original,
      uplifted,
      originalTreeDir: projectDir,
      upliftedTreeDir,
      runDir: projectRunDir,
      evidenceDir: projectRunDir && existsSync(join(projectRunDir, 'evidence')) ? join(projectRunDir, 'evidence') : null,
    });
  }

  const yieldReport = runDir ? readJson(join(runDir, 'yield.json')) : null;

  // The committed corpus manifest (read above, before run selection) is the decision source of
  // record when no local run records exist: it carries the measured SHAs, acceptance and improved
  // rules per project. A local run dir adds the journey-level detail on top.
  // Fill from the manifest only when the view IS the manifest's recorded run (or there are no
  // local runs at all): attributing one run's measurements to another run's view would be a lie.
  const manifestApplies = corpusManifest?.projects && (selectedRun === null || selectedRun === corpusManifest.run_id);
  if (manifestApplies) {
    const byId = new Map(corpusManifest.projects.map((entry) => [entry.project_id, entry]));
    for (const project of projects) {
      const entry = byId.get(project.id);
      if (!entry) continue;
      if (!project.decision) {
        project.decision = {
          project_id: entry.project_id,
          archetype: entry.archetype,
          framework: entry.framework,
          accepted: entry.accepted ?? false,
          category: entry.category ?? null,
          detail: ['from the committed corpus manifest (pilot/CORPUS.json); journey-level run records are not in this checkout'],
          improved_rules: entry.improved_rules ?? [],
          regressed_rules: [],
          new_security_findings: [],
          seeded_defects: entry.defects ?? [],
          original_sha: entry.original_sha ?? null,
          uplifted_sha: entry.uplift_sha ?? null,
          uplift_applied: entry.uplift_applied ?? [],
          record_source: 'manifest',
        };
      }
      // The manifest's SHAs are the record even when a run dir exists locally.
      project.decision.original_sha ??= entry.original_sha ?? null;
      project.decision.uplifted_sha ??= entry.uplift_sha ?? null;
    }
    // Projects the plan generates but this checkout never materialized (e.g. arms added after the
    // trees were last written to disk) are still corpus members: they are included, and their
    // measured trees are materialized from the plan at serve time.
    const known = new Set(projects.map((project) => project.id));
    for (const entry of corpusManifest.projects) {
      if (known.has(entry.project_id)) continue;
      projects.push({
        id: entry.project_id,
        spec: {
          archetype: entry.archetype,
          framework: { name: entry.framework },
          seeded_defects: entry.defects ?? [],
          required_rules: [],
        },
        specPath: null,
        originalTreeDir: join(corpusRoot, 'projects', entry.project_id),
        upliftedTreeDir: null,
        decision: {
          project_id: entry.project_id,
          archetype: entry.archetype,
          framework: entry.framework,
          accepted: entry.accepted ?? false,
          category: entry.category ?? null,
          detail: ['from the committed corpus manifest (pilot/CORPUS.json); the tree is materialized from the plan at serve time (not on disk in this checkout)'],
          improved_rules: entry.improved_rules ?? [],
          regressed_rules: [],
          new_security_findings: [],
          seeded_defects: entry.defects ?? [],
          original_sha: entry.original_sha ?? null,
          uplifted_sha: entry.uplift_sha ?? null,
          uplift_applied: entry.uplift_applied ?? [],
          record_source: 'manifest',
        },
        original: null,
        uplifted: null,
        evidenceDir: null,
        runDir: null,
      });
    }
    projects.sort((a, b) => a.id.localeCompare(b.id));
    // The manifest's run id is a valid selection in every view it applies to - including explicit
    // ?run= requests - or the live URLs the index generates would 404 on their own run.
    if (corpusManifest.run_id && !runs.includes(corpusManifest.run_id)) {
      runs.unshift(corpusManifest.run_id);
    }
  }
  const effectiveRunId = selectedRun ?? (manifestApplies ? corpusManifest?.run_id : null) ?? null;

  // Attribution (Paul, 2026-10-08): every artefact carries who/what made it. Unrecorded fields
  // are UNKNOWN, never implied. The pinned framework version comes from the repo's installed
  // dependency when the framework is a package.
  const repoRootGuess = dirname(corpusRoot);
  for (const project of projects) {
    const spec = project.spec ?? {};
    const frameworkName = spec.framework?.name ?? project.decision?.framework ?? 'unknown';
    let frameworkVersion = spec.framework?.version ?? null;
    if (frameworkName && frameworkName !== 'raw' && frameworkName !== 'unknown') {
      const pkgPath = join(repoRootGuess, 'node_modules', frameworkName, 'package.json');
      if (existsSync(pkgPath)) {
        try {
          const installed = JSON.parse(readFileSync(pkgPath, 'utf8')).version;
          frameworkVersion = frameworkVersion && frameworkVersion !== 'platform (no framework)' ? `${frameworkVersion} (installed: ${installed})` : `installed: ${installed}`;
        } catch {
          /* version stays as recorded */
        }
      }
    }
    const decision = project.decision;
    project.attribution = {
      model: spec.seeded_by ?? 'none — deterministic generator (no model wrote this artefact)',
      brief: `pilot/plan.json → ${project.id} (archetype: ${spec.archetype ?? decision?.archetype ?? 'unknown'})`,
      framework: frameworkVersion ? `${frameworkName} @ ${frameworkVersion}` : frameworkName,
      generator: corpusManifest?.generator
        ? `${corpusManifest.generator} @ ${corpusManifest.generated_at ?? 'UNKNOWN'}${corpusManifest.uplift_tool ? ` (target via ${corpusManifest.uplift_tool})` : ''}`
        : 'UNKNOWN (no corpus manifest)',
      acceptance: !decision
        ? 'UNKNOWN (not yet run)'
        : decision.accepted
          ? 'ACCEPTED PAIR'
          : `REJECTED ATTEMPT · ${decision.category ?? 'unspecified'}`,
    };
  }
  return { corpusRoot, runId: effectiveRunId, runs, projects, yieldReport: yieldReport ?? (corpusManifest ? { summary: corpusManifest.summary } : null), corpusManifest };
}

/**
 * The per-project view model for the index and evidence pages. `scan` is the owner-auth scan
 * result (see owner-auth.mjs); `verification` compares the trees on disk against the recorded SHAs.
 */
export function projectView(project, { scan = null, verification = null } = {}) {
  const spec = project.spec ?? {};
  const decision = project.decision ?? null;
  return {
    id: project.id,
    archetype: spec.archetype ?? decision?.archetype ?? 'unknown',
    archetypeTitle: spec.archetype_title ?? null,
    framework: spec.framework?.name ?? decision?.framework ?? 'unknown',
    frameworkVersion: spec.framework?.version ?? null,
    frameworkFamily: spec.framework?.family ?? decision?.framework_family ?? null,
    requiredRules: spec.required_rules ?? [],
    seededDefects: spec.seeded_defects ?? decision?.seeded_defects ?? [],
    hasRun: decision !== null,
    accepted: decision?.accepted ?? null,
    category: decision?.category ?? null,
    decisionDetail: decision?.detail ?? [],
    improvedRules: decision?.improved_rules ?? [],
    regressedRules: decision?.regressed_rules ?? [],
    newSecurityFindings: decision?.new_security_findings ?? [],
    upliftEdits: decision?.uplift_edits ?? null,
    upliftApplied: decision?.uplift_applied ?? [],
    upliftSkipped: decision?.uplift_skipped ?? [],
    upliftFailed: decision?.uplift_failed ?? [],
    originalSha: decision?.original_sha ?? null,
    upliftedSha: decision?.uplifted_sha ?? null,
    original: project.original,
    uplifted: project.uplifted,
    evidenceDir: project.evidenceDir,
    runDir: project.runDir,
    originalTreeDir: project.originalTreeDir,
    upliftedTreeDir: project.upliftedTreeDir,
    attribution: project.attribution ?? null,
    scan,
    verification,
  };
}

/** Index filters: archetype, framework, accept state (incl. per-category rejects), and rule. */
export function filterProjects(views, { archetype = null, framework = null, state = null, rule = null } = {}) {
  return views.filter((view) => {
    if (archetype && view.archetype !== archetype) return false;
    if (framework && view.framework !== framework) return false;
    if (state) {
      if (state === 'accepted' && view.accepted !== true) return false;
      if (state === 'rejected' && (view.accepted !== false || !view.hasRun)) return false;
      if (state === 'no-run' && view.hasRun) return false;
      if (!['accepted', 'rejected', 'no-run'].includes(state) && view.category !== state) return false;
    }
    if (rule) {
      const inRequired = view.requiredRules.includes(rule);
      const inImproved = view.improvedRules.includes(rule);
      if (!inRequired && !inImproved) return false;
    }
    return true;
  });
}
