/**
 * Provenance arms and the storage layout that keeps them apart.
 *
 * Why this file exists: the design brief (docs/design-brief-2026-10-08.md, sections 5 and 8)
 * requires that a rights-cleared arm and a quarantined arm never share a storage path, and that
 * moving an asset between arms cannot be used to launder its provenance. Both rules are enforced
 * here rather than by convention, and the enforcement is covered by test/arms.test.mjs.
 *
 * Vocabulary:
 *   arm            a rights class of corpus material (see ARMS below)
 *   trainable      the arm's material is permitted to reach a training corpus at all
 *   quarantined    the arm's material is held out of training pending sign-off
 *   approved       a specific row has an explicit per-asset approval (see record.mjs)
 *
 * The five rights the brief asks about (use / storage / training / distribution / trained-weight
 * publication) are recorded per asset in docs/provenance/assets/; this module only decides whether
 * a row is ALLOWED to reach training, which is the strictest of the five.
 */

export class ProvenanceError extends Error {
  constructor(code, message) {
    super(message);
    this.name = 'ProvenanceError';
    this.code = code;
  }
}

/** Single repository-relative root for all corpus material. */
export const DATA_ROOT = 'data';

/**
 * The arms. `storageRoot` is deliberately the arm id, so a path in a listing, a diff or a bucket
 * tells you which rights class the bytes belong to.
 *
 * eligibility:
 *   'requires-approval' - policy allows training, but only on rows carrying explicit approval
 *   'prohibited'        - held out of training pending named sign-off (the quarantined arms)
 *
 * publication (where the bytes LIVE - a separate axis from training eligibility):
 *   'public'     - the material lives in the public repo
 *   'quarantine' - the material lives in the private quarantine store (docs/quarantine.md)
 * A4 and A6 separate the axes: never trainable, but published publicly by design.
 * Training exclusion does not imply publication quarantine.
 */
export const ARMS = Object.freeze(
  Object.fromEntries(
    [
      {
        id: 'A1_self_generated',
        label: 'Self-generated originals',
        description:
          'Original projects generated by an appropriately licensed open-weight model or written by hand from synthetic briefs, with owned/rights-cleared dependencies.',
        eligibility: 'requires-approval',
      },
      {
        id: 'A2_mwg_uplift_deterministic',
        label: 'Deterministic, rights-cleared MWG uplift',
        description:
          'Uplift of an A1 original applied by our own rule specifications and tests, with no teacher model in the loop.',
        eligibility: 'requires-approval',
      },
      {
        id: 'A3_teacher_generated',
        label: 'Teacher-generated originals and uplift',
        description:
          'Any original or uplift authored by a hosted teacher model (Anthropic, OpenAI, Google, DeepSeek, Z.ai, ...). QUARANTINED until the specific account and endpoint terms are reviewed and signed off.',
        eligibility: 'prohibited',
      },
      {
        id: 'A4_clean_room_reproduction',
        label: 'Clean-room reproduction study',
        description:
          'Abstract functional requirements recorded by one researcher and implemented by another from public patterns. Never trainable: reproducibility does not settle rights in the target site.',
        eligibility: 'prohibited',
        publication: 'public',
      },
      {
        id: 'A5_black_box_reproduction',
        label: 'Black-box reproduction study',
        description:
          'Reproduction driven from screenshots, DOM or behaviour of a third-party site. QUARANTINED: avoiding source inspection is not a legal safe harbour.',
        eligibility: 'prohibited',
      },
      {
        id: 'A6_evaluation',
        label: 'Held-out evaluation material',
        description:
          'Evaluation briefs, their sites and their results. Never trainable: training on the test set destroys the primary endpoint.',
        eligibility: 'prohibited',
        publication: 'public',
      },
    ].map((arm) => [arm.id, Object.freeze({ ...arm, publication: arm.publication ?? (arm.eligibility === 'prohibited' ? 'quarantine' : 'public'), trainable: arm.eligibility === 'requires-approval', quarantined: arm.eligibility === 'prohibited', storageRoot: `${DATA_ROOT}/${arm.id}` })]),
  ),
);

export const ARM_IDS = Object.freeze(Object.keys(ARMS));

/** Arms whose material is held out of training by default. */
export const QUARANTINED_ARMS = Object.freeze(ARM_IDS.filter((id) => ARMS[id].quarantined));

export function assertKnownArm(armId) {
  if (!Object.prototype.hasOwnProperty.call(ARMS, armId)) {
    throw new ProvenanceError('UNKNOWN_ARM', `unknown provenance arm '${armId}' (known: ${ARM_IDS.join(', ')})`);
  }
  return armId;
}

export function armRoot(armId) {
  return ARMS[assertKnownArm(armId)].storageRoot;
}

/** Repository-relative root an asset in this arm must live under. */
export function defaultExcludedFromTraining(armId) {
  return ARMS[assertKnownArm(armId)].quarantined;
}

export function trainingEligibility(armId) {
  return ARMS[assertKnownArm(armId)].eligibility;
}

/**
 * Normalise a repository-relative path and reject anything that could escape the arm root:
 * absolute paths, `..` segments, empty segments and backslashes.
 */
export function normaliseRelativePath(relativePath) {
  if (typeof relativePath !== 'string' || relativePath.trim() === '') {
    throw new ProvenanceError('EMPTY_PATH', 'storage path must be a non-empty string');
  }
  if (relativePath.includes('\\')) {
    throw new ProvenanceError('PATH_BACKSLASH', `storage path must use forward slashes: '${relativePath}'`);
  }
  if (relativePath.startsWith('/')) {
    throw new ProvenanceError('ABSOLUTE_PATH', `storage path must be repository-relative: '${relativePath}'`);
  }
  const segments = relativePath.split('/');
  if (segments.some((segment) => segment === '' || segment === '.' || segment === '..')) {
    throw new ProvenanceError('PATH_TRAVERSAL', `storage path must not contain empty, '.' or '..' segments: '${relativePath}'`);
  }
  return segments.join('/');
}

/** Absolute-in-repo storage path for one asset: `<data root>/<arm>/<relative>`. */
export function resolveStoragePath(armId, relativePath) {
  return `${armRoot(armId)}/${normaliseRelativePath(relativePath)}`;
}

/** True when `candidate` is inside `root` (compared on whole path segments). */
export function isInside(root, candidate) {
  return candidate === root || candidate.startsWith(`${root}/`);
}

/**
 * An asset's storage path must sit inside its own arm. This is the check that stops an approved
 * arm and a quarantined arm from sharing a directory: sharing would require one of them to be
 * outside its own root, which fails here.
 */
export function assertAssetPath(record) {
  const expected = armRoot(record.arm);
  const actual = normaliseRelativePath(record.storage_path);
  if (!isInside(expected, actual)) {
    throw new ProvenanceError(
      'CROSS_ARM_PATH',
      `asset '${record.id ?? '(no id)'}' is in arm ${record.arm} but its storage_path '${actual}' is outside '${expected}'`,
    );
  }
  return actual;
}

/**
 * Two arms must never map to the same root or to nested roots. Call with the layout the corpus
 * actually uses (arm id -> root) before a dataset is materialised.
 */
export function assertArmRootsDistinct(layout = Object.fromEntries(ARM_IDS.map((id) => [id, armRoot(id)]))) {
  const entries = Object.entries(layout);
  for (const [armA, rootA] of entries) {
    assertKnownArm(armA);
    normaliseRelativePath(rootA);
    for (const [armB, rootB] of entries) {
      if (armA === armB) continue;
      if (rootA === rootB || isInside(rootA, rootB)) {
        throw new ProvenanceError(
          'SHARED_ARM_ROOT',
          `arms ${armA} and ${armB} share a storage root ('${rootA}' vs '${rootB}'); each arm needs its own directory tree`,
        );
      }
    }
  }
  return layout;
}

/**
 * Moving an asset between arms is prohibited outright - including from a quarantined arm into an
 * approved one. Provenance cannot be laundered by relocating bytes: if restricted material needs
 * to become trainable, it must be regenerated under the approved arm with its own provenance
 * record, and the regeneration itself is the thing that is reviewed.
 */
export function moveToArm() {
  throw new ProvenanceError(
    'CROSS_ARM_MOVEMENT_PROHIBITED',
    'assets may not move between provenance arms; regenerate the asset under the target arm with its own provenance record instead',
  );
}

/** Renaming or reorganising inside one arm is fine. */
export function renameWithinArm(record, newRelativePath) {
  assertKnownArm(record.arm);
  return { ...record, storage_path: resolveStoragePath(record.arm, newRelativePath) };
}

/** Policy answer for one row: eligible arm AND explicit per-row approval AND not excluded. */
export function isTrainable(record) {
  if (!Object.prototype.hasOwnProperty.call(ARMS, record.arm)) return false;
  if (!ARMS[record.arm].trainable) return false;
  if (record.excluded_from_training !== false) return false;
  return record.approved_for_training === true;
}

export function assertMayTrain(record) {
  assertKnownArm(record.arm);
  const arm = ARMS[record.arm];
  if (!arm.trainable) {
    throw new ProvenanceError('ARM_QUARANTINED', `arm ${arm.id} is quarantined: ${arm.description}`);
  }
  if (record.excluded_from_training !== false) {
    throw new ProvenanceError('EXCLUDED_FROM_TRAINING', `asset '${record.id}' is excluded_from_training`);
  }
  if (record.approved_for_training !== true) {
    throw new ProvenanceError('NOT_APPROVED', `asset '${record.id}' has no explicit training approval`);
  }
  return true;
}
